### ISSUE TITLE
Response mapPoint from avengers has changed x and y

### ISSUE THREAD

**Issue by marosstudenic** [zemacik/PanaxeoCodingArena2023_BattleshipsServer#4]
Avenger result is returning 

"avengerResult": [
        {
            "mapPoint": {
                "x": **COLUMN**,
                "y": **ROW**
            },
            "hit": false
        }
    ]

but it should be 
"avengerResult": [
        {
            "mapPoint": {
                "x": **ROW**,
                "y": **COLUMN**
            },
            "hit": false
        }
    ]

![image](https://github.com/zemacik/PanaxeoCodingArena2023_BattleshipsServer/assets/15611916/1f00f125-fbb5-4877-a94b-811ae2fd6bac)

**Comment by zemacik** [comment]
Resolved in #5

**Comment by zemacik** [comment]
@marosstudenic Dakujem za upozornenie.
