### ISSUE TITLE
Using ironman ability gives incorrect data

### ISSUE THREAD

**Issue by Em1tt** [zemacik/PanaxeoCodingArena2023_BattleshipsServer#6]
When using the Iron Man ability, it seems that the values supplied in `avengerResult` are swapped (`x` has the Y value, and `y` has the X value)  
Below is the image of the board  
![image](https://github.com/zemacik/PanaxeoCodingArena2023_BattleshipsServer/assets/55552821/d00c1f31-c274-491f-95e9-bf4caa90dd27)
Below is the `avengerResult` data
![image](https://github.com/zemacik/PanaxeoCodingArena2023_BattleshipsServer/assets/55552821/fe03778e-13f4-4239-9729-6dc6a5d8123f)

**Comment by zemacik** [comment]
When was the last time you fetched new version?

Because on 12/11/2023 9:26 PM I wrote;
Ak niekto pouzivate ten server, tak si stiahnite novsiu verziu. Bol tam bug. (Dakujem Maros za upozornenie)

So the problem should be solved by now.
Is it?

**Comment by Em1tt** [comment]
Oh, I can confirm that it is fixed in the new version. I installed it on the same day, but I must've messed up and was still running the old version.
